spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@211.238.142.194:1521/xe
    username: final_orauser3
    password: gclass
    
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 7070
  servlet:
    jsp:
      init-parameters:
        development: true
